### PR TITLE
Animate notification in and out

### PR DESCRIPTION
**Pull request by meriadec**
This PR is related to #38 .
Here is the result: (it _seems_ laggy on the gif, but it's only the gif encoding, the real animation is pretty smooth)

output

Note that I didn't achieved to use the notification in real condition (got no sonarr server, so I preferred mock a notification on the configure page).
Tell me if it works well in real conditions!

### CODE REVIEW

**Comment by arnif** [comment]
Hi, thanks for showing this project interest ! 

I tested this on a real instance and the animation is really nice, however the Component is always rendering a `<View />` which means this looks like this when there is no notification to display:

screen shot 2016-10-15 at 22 41 14

I've setup a small Digital Ocean instance to test stuff on. You're welcome to use it if you are willing to continue working on this. I would greatly appreciate that.

URL: `http://139.59.166.50:8989`
API key: `5287e9314d904a499739187b8dd38c08` (can also be found under Settings -> General)

The notifications appear when the magnifying glass is pressed and in other various places. See `app/lib/inAppNotificationMiddleware.js` for the list of actions that dispatch notifications.

Thank you very much for your contribution.

**Comment by meriadec** [comment]
Great idea, so yep I will continue. I will update the PR today I think.

**Comment by meriadec** [comment]
Here is the result:

animationg

**Comment by arnif** [comment]
This is awesome. Thank you very much ! :)

**Pull request merged**
